### ISSUE TITLE
No such file or directory: <ArduinoJson.h>

### ISSUE THREAD

**Issue by pjirsa** [noopkat/mxchip-gifs#19]
Anyone know why i am getting this error when trying to upload the device code to my MXChip device?

**Comment by pjirsa** [comment]
I was able to resolve this by using the Arduino library manager to install the correct 5.13.5 version of the ArduinoJson library.

**Comment by noopkat** [comment]
@pjirsa I'm glad you got it sorted out! 💯 If you have any more feedback about his project and the documentation, please don't hesitate to open another issue 🙇‍♀
